export enum DownloadMutationTypes {
  ADD_FILE = "ADD_FILE",
  ADD_FILES = "ADD_FILES",
  DOWNLOAD__UPLOAD_ID = "DOWNLOAD__UPLOAD_ID",
  HTTP_STATUE_CODE = "HTTP_STATUE_CODE",
  FETCHER_STATE = "FETCHER_STATE",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_STATE = "AUTH_STATE",
  AUTH_TOKEN = "SET_AUTH_TOKEN",
}
