export enum DownloadMutationTypes {
  ADD_FILE = "DOWNLOAD__ADD_FILE",
  ADD_FILES = "DOWNLOAD__ADD_FILES",
  UPLOAD_ID = "DOWNLOAD__UPLOAD_ID",
  HTTP_CODE = "DOWNLOAD__HTTP_CODE",
  FETCH_STATE = "DOWNLOAD__FETCH_STATE",
  AUTH_REQUIRED = "DOWNLOAD__AUTH_REQUIRED",
  AUTH_STATE = "DOWNLOAD__AUTH_STATE",
  AUTH_TOKEN = "DOWNLOAD__SET_AUTH_TOKEN",
}
