## PRODUCTION
FROM golang:1.15.6 as files-service-builder
LABEL app_name=kabaliserv_cloudshare
LABEL stage=builder
WORKDIR /app
COPY . .
ENV CGO_ENABLED=0
RUN go mod download
RUN go mod verify
RUN go build -o cloudshare

FROM alpine:3.14.6
ARG VERSION
LABEL app_name=kabaliserv_cloudshare
LABEL stage=prod
LABEL version=${VERSION}
WORKDIR /app
COPY --from=files-service-builder /app/cloudshare /
ENTRYPOINT ["/cloudshare"]
