export enum DownloadActionTypes {
  FETCH_METADADTA = "DOWNLOAD__FETCH_METADADTA",
  GET_FILE = "DOWNLOAD__GET_FILE",
  GET_FILES = "DOWNLOAD__GET_FILES",
  GET_AUTH = "DOWNLOAD__GET_AUTH",
  AUTH_IS_REQUIRED = "DOWNLOAD__AUTH_IS_REQUIRED",
}
