export enum UploadMutationTypes {
  PUSH_FILE = "UPLOAD__PUSH_FILE",
  REMOVE_FILE = "UPLOAD__REMOVE_FILE",
  UPLOAD_ID = "UPLOAD_UPLOAD_ID",
  PROCESS_STATE = "UPLOAD__PROCESS_STATE",
  PROCESS_CACHE_STATE = "UPLOAD__PROCESS_CACHE_STATE",
  EXPIRATION = "UPLOAD__EXPIRATION",
  PASSWORD = "UPLOAD__PASSWORD",
  ADD_BYTES_UPLOADED = "UPLOAD__ADD_BYTES_UPLOADED",
}
