export enum UploadMutationTypes {
  PUSH_FILE = "UPLOAD__PUSH_FILE",
  REMOVE_FILE = "REMOVE_FILE",
  UPLOAD_ID = "UPLOAD_UPLOAD_ID",
  STATUS = "UPLOAD__STATUS",
  CACHE_STATUS = "UPLOAD__CACHE_STATUS",
  EXPIRATION = "UPLOAD__EXPIRATION",
  PASSWORD = "UPLOAD__PASSWORD",
}
