export enum UploadMutationTypes {
  ADD_FILE = "ADD_FILE",
  REMOVE_FILE = "REMOVE_FILE",
  SET_UPLOAD_ID = "SET_UPLOAD_ID",
  SET_UPLOAD_STATE = "SET_UPLOAD_STATE",
  SET_UPLOAD_CACHE_STATE = "SET_UPLOAD_CACHE_STATE",
  UPDATE_EXPIRATION = "UPDATE_EXPIRATION",
  UPDATE_PASSWORD = "UPDATE_PASSWORD",
}
