// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package files

import (
	context "context"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilesServiceClient is the client API for FilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesServiceClient interface {
	FilesExist(ctx context.Context, in *StoreFilesId, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	DeleteFiles(ctx context.Context, in *StoreFilesId, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	MoveFilesToUploadStore(ctx context.Context, in *MoveTo, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	GetMetaCacheFile(ctx context.Context, in *FileId, opts ...grpc.CallOption) (*MetaFile, error)
}

type filesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesServiceClient(cc grpc.ClientConnInterface) FilesServiceClient {
	return &filesServiceClient{cc}
}

func (c *filesServiceClient) FilesExist(ctx context.Context, in *StoreFilesId, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/files.FilesService/FilesExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) DeleteFiles(ctx context.Context, in *StoreFilesId, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/files.FilesService/DeleteFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) MoveFilesToUploadStore(ctx context.Context, in *MoveTo, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/files.FilesService/MoveFilesToUploadStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetMetaCacheFile(ctx context.Context, in *FileId, opts ...grpc.CallOption) (*MetaFile, error) {
	out := new(MetaFile)
	err := c.cc.Invoke(ctx, "/files.FilesService/GetMetaCacheFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesServiceServer is the server API for FilesService service.
// All implementations must embed UnimplementedFilesServiceServer
// for forward compatibility
type FilesServiceServer interface {
	FilesExist(context.Context, *StoreFilesId) (*wrappers.BoolValue, error)
	DeleteFiles(context.Context, *StoreFilesId) (*wrappers.BoolValue, error)
	MoveFilesToUploadStore(context.Context, *MoveTo) (*wrappers.BoolValue, error)
	GetMetaCacheFile(context.Context, *FileId) (*MetaFile, error)
	mustEmbedUnimplementedFilesServiceServer()
}

// UnimplementedFilesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilesServiceServer struct {
}

func (UnimplementedFilesServiceServer) FilesExist(context.Context, *StoreFilesId) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilesExist not implemented")
}
func (UnimplementedFilesServiceServer) DeleteFiles(context.Context, *StoreFilesId) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFiles not implemented")
}
func (UnimplementedFilesServiceServer) MoveFilesToUploadStore(context.Context, *MoveTo) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveFilesToUploadStore not implemented")
}
func (UnimplementedFilesServiceServer) GetMetaCacheFile(context.Context, *FileId) (*MetaFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaCacheFile not implemented")
}
func (UnimplementedFilesServiceServer) mustEmbedUnimplementedFilesServiceServer() {}

// UnsafeFilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesServiceServer will
// result in compilation errors.
type UnsafeFilesServiceServer interface {
	mustEmbedUnimplementedFilesServiceServer()
}

func RegisterFilesServiceServer(s grpc.ServiceRegistrar, srv FilesServiceServer) {
	s.RegisterService(&FilesService_ServiceDesc, srv)
}

func _FilesService_FilesExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFilesId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).FilesExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/FilesExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).FilesExist(ctx, req.(*StoreFilesId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_DeleteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFilesId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).DeleteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/DeleteFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).DeleteFiles(ctx, req.(*StoreFilesId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_MoveFilesToUploadStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).MoveFilesToUploadStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/MoveFilesToUploadStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).MoveFilesToUploadStore(ctx, req.(*MoveTo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetMetaCacheFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetMetaCacheFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/files.FilesService/GetMetaCacheFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetMetaCacheFile(ctx, req.(*FileId))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesService_ServiceDesc is the grpc.ServiceDesc for FilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "files.FilesService",
	HandlerType: (*FilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilesExist",
			Handler:    _FilesService_FilesExist_Handler,
		},
		{
			MethodName: "DeleteFiles",
			Handler:    _FilesService_DeleteFiles_Handler,
		},
		{
			MethodName: "MoveFilesToUploadStore",
			Handler:    _FilesService_MoveFilesToUploadStore_Handler,
		},
		{
			MethodName: "GetMetaCacheFile",
			Handler:    _FilesService_GetMetaCacheFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/files.proto",
}
