// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: protos/files.proto

package files

import (
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StoreFilesId_Store int32

const (
	StoreFilesId_UNKNOWN StoreFilesId_Store = 0
	StoreFilesId_UPLOAD  StoreFilesId_Store = 1
	StoreFilesId_CACHE   StoreFilesId_Store = 2
)

// Enum value maps for StoreFilesId_Store.
var (
	StoreFilesId_Store_name = map[int32]string{
		0: "UNKNOWN",
		1: "UPLOAD",
		2: "CACHE",
	}
	StoreFilesId_Store_value = map[string]int32{
		"UNKNOWN": 0,
		"UPLOAD":  1,
		"CACHE":   2,
	}
)

func (x StoreFilesId_Store) Enum() *StoreFilesId_Store {
	p := new(StoreFilesId_Store)
	*p = x
	return p
}

func (x StoreFilesId_Store) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreFilesId_Store) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_files_proto_enumTypes[0].Descriptor()
}

func (StoreFilesId_Store) Type() protoreflect.EnumType {
	return &file_protos_files_proto_enumTypes[0]
}

func (x StoreFilesId_Store) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreFilesId_Store.Descriptor instead.
func (StoreFilesId_Store) EnumDescriptor() ([]byte, []int) {
	return file_protos_files_proto_rawDescGZIP(), []int{1, 0}
}

type FileId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FileId) Reset() {
	*x = FileId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileId) ProtoMessage() {}

func (x *FileId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileId.ProtoReflect.Descriptor instead.
func (*FileId) Descriptor() ([]byte, []int) {
	return file_protos_files_proto_rawDescGZIP(), []int{0}
}

func (x *FileId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StoreFilesId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store StoreFilesId_Store `protobuf:"varint,1,opt,name=store,proto3,enum=files.StoreFilesId_Store" json:"store,omitempty"`
	Ids   []string           `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *StoreFilesId) Reset() {
	*x = StoreFilesId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFilesId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFilesId) ProtoMessage() {}

func (x *StoreFilesId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFilesId.ProtoReflect.Descriptor instead.
func (*StoreFilesId) Descriptor() ([]byte, []int) {
	return file_protos_files_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFilesId) GetStore() StoreFilesId_Store {
	if x != nil {
		return x.Store
	}
	return StoreFilesId_UNKNOWN
}

func (x *StoreFilesId) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type MoveTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCacheId string `protobuf:"bytes,1,opt,name=fromCacheId,proto3" json:"fromCacheId,omitempty"`
	ToUploadId  string `protobuf:"bytes,2,opt,name=toUploadId,proto3" json:"toUploadId,omitempty"`
}

func (x *MoveTo) Reset() {
	*x = MoveTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTo) ProtoMessage() {}

func (x *MoveTo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTo.ProtoReflect.Descriptor instead.
func (*MoveTo) Descriptor() ([]byte, []int) {
	return file_protos_files_proto_rawDescGZIP(), []int{2}
}

func (x *MoveTo) GetFromCacheId() string {
	if x != nil {
		return x.FromCacheId
	}
	return ""
}

func (x *MoveTo) GetToUploadId() string {
	if x != nil {
		return x.ToUploadId
	}
	return ""
}

type MetaFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type         string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Size         int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	LastModified int64  `protobuf:"varint,4,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
}

func (x *MetaFile) Reset() {
	*x = MetaFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaFile) ProtoMessage() {}

func (x *MetaFile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaFile.ProtoReflect.Descriptor instead.
func (*MetaFile) Descriptor() ([]byte, []int) {
	return file_protos_files_proto_rawDescGZIP(), []int{3}
}

func (x *MetaFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetaFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaFile) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

var File_protos_files_proto protoreflect.FileDescriptor

var file_protos_files_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x06, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x41,
	0x43, 0x48, 0x45, 0x10, 0x02, 0x22, 0x4a, 0x0a, 0x06, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x12,
	0x20, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x64, 0x22, 0x6a, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x73,
	0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x32, 0x8e, 0x02,
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49,
	0x64, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x13,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x49, 0x64, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x16, 0x4d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x54, 0x6f,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0d, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x43, 0x61, 0x63, 0x68, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0d, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x00, 0x42, 0x41,
	0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6c,
	0x73, 0x6f, 0x6e, 0x2d, 0x6b, 0x62, 0x73, 0x2f, 0x74, 0x6d, 0x70, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_files_proto_rawDescOnce sync.Once
	file_protos_files_proto_rawDescData = file_protos_files_proto_rawDesc
)

func file_protos_files_proto_rawDescGZIP() []byte {
	file_protos_files_proto_rawDescOnce.Do(func() {
		file_protos_files_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_files_proto_rawDescData)
	})
	return file_protos_files_proto_rawDescData
}

var file_protos_files_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_files_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_files_proto_goTypes = []interface{}{
	(StoreFilesId_Store)(0),    // 0: files.StoreFilesId.Store
	(*FileId)(nil),             // 1: files.FileId
	(*StoreFilesId)(nil),       // 2: files.StoreFilesId
	(*MoveTo)(nil),             // 3: files.MoveTo
	(*MetaFile)(nil),           // 4: files.MetaFile
	(*wrappers.BoolValue)(nil), // 5: google.protobuf.BoolValue
}
var file_protos_files_proto_depIdxs = []int32{
	0, // 0: files.StoreFilesId.store:type_name -> files.StoreFilesId.Store
	2, // 1: files.FilesService.FilesExist:input_type -> files.StoreFilesId
	2, // 2: files.FilesService.DeleteFiles:input_type -> files.StoreFilesId
	3, // 3: files.FilesService.MoveFilesToUploadStore:input_type -> files.MoveTo
	1, // 4: files.FilesService.GetMetaCacheFile:input_type -> files.FileId
	5, // 5: files.FilesService.FilesExist:output_type -> google.protobuf.BoolValue
	5, // 6: files.FilesService.DeleteFiles:output_type -> google.protobuf.BoolValue
	5, // 7: files.FilesService.MoveFilesToUploadStore:output_type -> google.protobuf.BoolValue
	4, // 8: files.FilesService.GetMetaCacheFile:output_type -> files.MetaFile
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_files_proto_init() }
func file_protos_files_proto_init() {
	if File_protos_files_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_files_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_files_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFilesId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_files_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_files_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_files_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_files_proto_goTypes,
		DependencyIndexes: file_protos_files_proto_depIdxs,
		EnumInfos:         file_protos_files_proto_enumTypes,
		MessageInfos:      file_protos_files_proto_msgTypes,
	}.Build()
	File_protos_files_proto = out.File
	file_protos_files_proto_rawDesc = nil
	file_protos_files_proto_goTypes = nil
	file_protos_files_proto_depIdxs = nil
}
