// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protos/meta.proto

package meta

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaUpload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Auth      bool   `protobuf:"varint,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Active    bool   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	ExpireAt  string `protobuf:"bytes,4,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	Permanent bool   `protobuf:"varint,5,opt,name=permanent,proto3" json:"permanent,omitempty"`
}

func (x *MetaUpload) Reset() {
	*x = MetaUpload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaUpload) ProtoMessage() {}

func (x *MetaUpload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaUpload.ProtoReflect.Descriptor instead.
func (*MetaUpload) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{0}
}

func (x *MetaUpload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetaUpload) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *MetaUpload) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MetaUpload) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *MetaUpload) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

type MetaFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type         string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size         int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	LastModified int64  `protobuf:"varint,5,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
}

func (x *MetaFile) Reset() {
	*x = MetaFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaFile) ProtoMessage() {}

func (x *MetaFile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaFile.ProtoReflect.Descriptor instead.
func (*MetaFile) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{1}
}

func (x *MetaFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetaFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetaFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaFile) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

type UploadId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UploadId) Reset() {
	*x = UploadId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadId) ProtoMessage() {}

func (x *UploadId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadId.ProtoReflect.Descriptor instead.
func (*UploadId) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{2}
}

func (x *UploadId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UploadMetaFiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*MetaFile `protobuf:"bytes,15,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *UploadMetaFiles) Reset() {
	*x = UploadMetaFiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetaFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetaFiles) ProtoMessage() {}

func (x *UploadMetaFiles) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetaFiles.ProtoReflect.Descriptor instead.
func (*UploadMetaFiles) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{3}
}

func (x *UploadMetaFiles) GetFiles() []*MetaFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type UploadFilesId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadId string   `protobuf:"bytes,1,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	FilesId  []string `protobuf:"bytes,15,rep,name=filesId,proto3" json:"filesId,omitempty"`
}

func (x *UploadFilesId) Reset() {
	*x = UploadFilesId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFilesId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFilesId) ProtoMessage() {}

func (x *UploadFilesId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFilesId.ProtoReflect.Descriptor instead.
func (*UploadFilesId) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFilesId) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadFilesId) GetFilesId() []string {
	if x != nil {
		return x.FilesId
	}
	return nil
}

type UploadAndFileId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadId string `protobuf:"bytes,1,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	FileId   string `protobuf:"bytes,2,opt,name=fileId,proto3" json:"fileId,omitempty"`
}

func (x *UploadAndFileId) Reset() {
	*x = UploadAndFileId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAndFileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAndFileId) ProtoMessage() {}

func (x *UploadAndFileId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAndFileId.ProtoReflect.Descriptor instead.
func (*UploadAndFileId) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{5}
}

func (x *UploadAndFileId) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadAndFileId) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type TokenCred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadId string `protobuf:"bytes,1,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenCred) Reset() {
	*x = TokenCred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_meta_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenCred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCred) ProtoMessage() {}

func (x *TokenCred) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCred.ProtoReflect.Descriptor instead.
func (*TokenCred) Descriptor() ([]byte, []int) {
	return file_protos_meta_proto_rawDescGZIP(), []int{6}
}

func (x *TokenCred) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *TokenCred) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_protos_meta_proto protoreflect.FileDescriptor

var file_protos_meta_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x4d, 0x65,
	0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x65, 0x6e, 0x74, 0x22, 0x7a,
	0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x1a, 0x0a, 0x08, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22,
	0x45, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a,
	0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xbe, 0x02, 0x0a,
	0x0b, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x1a, 0x10, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x1a, 0x0e, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64,
	0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x0f,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x1a,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x42, 0x46, 0x5a,
	0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6c, 0x73,
	0x6f, 0x6e, 0x2d, 0x6b, 0x62, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_meta_proto_rawDescOnce sync.Once
	file_protos_meta_proto_rawDescData = file_protos_meta_proto_rawDesc
)

func file_protos_meta_proto_rawDescGZIP() []byte {
	file_protos_meta_proto_rawDescOnce.Do(func() {
		file_protos_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_meta_proto_rawDescData)
	})
	return file_protos_meta_proto_rawDescData
}

var file_protos_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_meta_proto_goTypes = []interface{}{
	(*MetaUpload)(nil),         // 0: meta.MetaUpload
	(*MetaFile)(nil),           // 1: meta.MetaFile
	(*UploadId)(nil),           // 2: meta.UploadId
	(*UploadMetaFiles)(nil),    // 3: meta.UploadMetaFiles
	(*UploadFilesId)(nil),      // 4: meta.UploadFilesId
	(*UploadAndFileId)(nil),    // 5: meta.UploadAndFileId
	(*TokenCred)(nil),          // 6: meta.TokenCred
	(*wrappers.BoolValue)(nil), // 7: google.protobuf.BoolValue
}
var file_protos_meta_proto_depIdxs = []int32{
	1, // 0: meta.UploadMetaFiles.files:type_name -> meta.MetaFile
	2, // 1: meta.MetaService.GetMetaUpload:input_type -> meta.UploadId
	5, // 2: meta.MetaService.GetUploadMetaFile:input_type -> meta.UploadAndFileId
	2, // 3: meta.MetaService.GetUploadMetaFiles:input_type -> meta.UploadId
	2, // 4: meta.MetaService.UploadIsActive:input_type -> meta.UploadId
	6, // 5: meta.MetaService.TokenIsValid:input_type -> meta.TokenCred
	0, // 6: meta.MetaService.GetMetaUpload:output_type -> meta.MetaUpload
	1, // 7: meta.MetaService.GetUploadMetaFile:output_type -> meta.MetaFile
	3, // 8: meta.MetaService.GetUploadMetaFiles:output_type -> meta.UploadMetaFiles
	7, // 9: meta.MetaService.UploadIsActive:output_type -> google.protobuf.BoolValue
	7, // 10: meta.MetaService.TokenIsValid:output_type -> google.protobuf.BoolValue
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_meta_proto_init() }
func file_protos_meta_proto_init() {
	if File_protos_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaUpload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetaFiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFilesId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAndFileId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_meta_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenCred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_meta_proto_goTypes,
		DependencyIndexes: file_protos_meta_proto_depIdxs,
		MessageInfos:      file_protos_meta_proto_msgTypes,
	}.Build()
	File_protos_meta_proto = out.File
	file_protos_meta_proto_rawDesc = nil
	file_protos_meta_proto_goTypes = nil
	file_protos_meta_proto_depIdxs = nil
}
